data:
  path: dataset/student_performance.csv
  target_column: Performance Index
  test_size: 0.2
model:
  activation: relu
  hidden_layers:
  - 16
  - 16
training:
  batch_size: 16
  learning_rate: 0.001
  num_epochs: 500
  patience: null
